baseURL = 'https://lookharm.github.io/blog'
locale = 'en-us'
title = 'Blog'
theme = 'xmin'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 2

